'use strict'

export const SET_PERMISSIONLIST = 'SET_PERMISSIONLIST'
export const SET_ROLELIST = 'SET_ROLELIST'
export const SHOW_EDIT_WINDOW = 'SHOW_EDIT_WINDOW'
export const REMOVE_FROM_ROLELIST = 'REMOVE_FROM_ROLELIST'
export const SET_ROLE_PROPERT_BY_INDEX = 'SET_ROLE_PROPERT_BY_INDEX'
