export const SET_SELECT_WEATHER_LIST = 'SET_SELECT_WEATHER_LIST'
export const SET_WEATHER_PAGE_LIST = 'SET_WEATHER_PAGE_LIST'
export const REMOVE_WEATHER_LIST = 'REMOVE_WEATHER_LIST'
export const SPLICE_WEATHER_LIST = 'SPLICE_WEATHER_LIST'
