'use strict'

export const GET_SERVER_LIST = 'GET_SERVER_LIST'
export const GET_EXAMINE_LIST = 'GET_EXAMINE_LIST'
export const GET_UPGRADE_LIST = 'GET_UPGRADE_LIST'
export const GET_AUTODELETE_LIST = 'GET_AUTODELETE_LIST'
export const UPDATE_LOADING_STATUS = 'UPDATE_LOADING_STATUS'
export const GET_LICENSE = 'GET_LICENSE'
