'use strict'

export const SET_PERMISSIONSLIST = 'SET_PERMISSIONSLIST'
export const SET_EDITWINDOW = 'SET_EDITWINDOW'
export const REMOVE_FROM_PERMISSIONSLIST = 'REMOVE_FROM_PERMISSIONSLIST'
export const SET_ROLE_PERMISSION_BY_INDEX = 'SET_ROLE_PERMISSION_BY_INDEX'
