'use strict'

// export const SET_DRUGLIST = 'SET_DRUGLIST'
export const GET_DRUGS_PAGE_LIST = 'GET_DRUGS_PAGE_LIST'
export const SHOW_EDIT_WINDOW = 'SHOW_EDIT_WINDOW'
export const SHOW_STOCK_WINDOW = 'SHOW_STOCK_WINDOW'
export const UPDATE_LOADING_STATUS = 'UPDATE_LOADING_STATUS'
export const GET_DRUGS_TYPE_LIST = 'GET_DRUGS_TYPE_LIST'
export const SHOW_GALLERY_WINDOW = 'SHOW_GALLERY_WINDOW'
