'use strict'

export const SHOW_MARQUEE_EDIT = 'SHOW_MARQUEE_EDIT'
export const ADD_MARQUEE = 'ADD_MARQUEE'
export const GET_MARQUEE = 'GET_MARQUEE'
export const REMOVE_MARQUEE = 'REMOVE_MARQUEE'
export const EDIT_MARQUEE = 'EDIT_MARQUEE'
export const UPDATE_MARQUEE_STATUS = 'UPDATE_MARQUEE_STATUS'
export const SET_STATUS_COUNT = 'SET_STATUS_COUNT'
