'use strict'

export const SET_USER_LIST = 'SET_USER_LIST'
export const SHOW_EDIT_WINDOW = 'SHOW_EDIT_WINDOW'
export const REMOVE_FROM_USERLIST = 'REMOVE_FROM_USERLIST'
export const SET_GROUP_LIST = 'SET_GROUP_LIST'
export const SET_USER_PROPERTY_BY_INDEX = 'SET_USER_PROPERTY_BY_INDEX'
