'use strict'

export const GET_PRODUCTS_PAGE_LIST = 'GET_PRODUCTS_PAGE_LIST'
export const SHOW_EDIT_WINDOW = 'SHOW_EDIT_WINDOW'
export const SHOW_STOCK_WINDOW = 'SHOW_STOCK_WINDOW'
export const UPDATE_LOADING_STATUS = 'UPDATE_LOADING_STATUS'
export const GET_PRODUCTS_TYPE_LIST = 'GET_PRODUCTS_TYPE_LIST'
export const SHOW_GALLERY_WINDOW = 'SHOW_GALLERY_WINDOW'
